# Generated by Django 3.1.7 on 2021-04-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="published_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("surname", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Не ищу работу", "Close"),
                            ("Рассматриваю предложения", "Passive"),
                            ("Ищу работу", "Active"),
                        ],
                        default="Не ищу работу",
                        max_length=32,
                    ),
                ),
                ("salary", models.IntegerField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("Стажер", "Trainee"),
                            ("Джуниор", "Junior"),
                            ("Миддл", "Middle"),
                            ("Синьор", "Senior"),
                            ("Лид", "Lead"),
                        ],
                        default="Стажер",
                        max_length=32,
                    ),
                ),
                ("education", models.TextField()),
                ("experience", models.TextField()),
                ("portfolio", models.URLField(blank=True)),
                (
                    "specialty",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="vacancies.specialty"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resume", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
